In [1]:
import numpy as np

In [2]:
# numpy的数组与python内建的数组不同，其运行更快，并占用内存更少
# numpy的向量化数据操作比纯python的等价实现（循环）速度上要快一到两个数量级（甚至更多）
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list = [x*2 for x in my_list]

CPU times: user 22.7 ms, sys: 47.7 ms, total: 70.4 ms
Wall time: 71.6 ms
CPU times: user 956 ms, sys: 152 ms, total: 1.11 s
Wall time: 1.11 s


In [3]:
# 生成随机数组，data是一个ndarray对象，是numpy的N-维数组
data = np.random.randn(2, 3)
data

array([[-0.40880482,  1.99205709, -0.91199049],
       [ 1.00161195,  0.06735692,  0.91297194]])

In [4]:
# numpy中的数组操作，不必写循环
data * 10

array([[-4.08804817, 19.92057093, -9.11990492],
       [10.01611951,  0.67356922,  9.1297194 ]])

In [5]:
# numpy中的数组操作，不必写循环
data + data

array([[-0.81760963,  3.98411419, -1.82398098],
       [ 2.0032239 ,  0.13471384,  1.82594388]])

In [6]:
# ndim属性表示ndarray的维度
data.ndim

2

In [7]:
# shape属性表示ndarray每一维的数量
data.shape

(2, 3)

In [8]:
# dtype属性表示ndarrau的数据类型
data.dtype

dtype('float64')