In [1]:
import numpy as np
# 通用函数，可称作ufunc，是一种在ndarray数据中进行逐元素操作的函数，通用函数通常就是鉴定单函数的向量化封装。

In [2]:
arr = np.arange(10)
np.sqrt(arr)  # 平方根

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
np.exp(arr)  # 以e为底的幂运算

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [4]:
x = np.array([-0.48, -1.43,  0.18, -0.48, -0.17, 1.15, -1.46, -0.07])  # x = np.random.randn(8)
y = np.array([-1.18,  1.43, -0.65, -1.44,  0.20, 0.68,  0.86,  0.08])  # y = np.random.randn(8)
np.maximum(x, y)

array([-0.48,  1.43,  0.18, -0.48,  0.2 ,  1.15,  0.86,  0.08])

In [5]:
np.add(x, y)

array([-1.66,  0.  , -0.47, -1.92,  0.03,  1.83, -0.6 ,  0.01])

In [6]:
arr = np.array([-10.85, -1.80, -0.37, -6.58, 8.89, 5.83, 3.21])  # arr = np.random.randn(7) * 5

In [7]:
remainder, whole_part = np.modf(arr)  # python内建的divmod()的向量版
remainder

array([-0.85, -0.8 , -0.37, -0.58,  0.89,  0.83,  0.21])

In [8]:
whole_part

array([-10.,  -1.,  -0.,  -6.,   8.,   5.,   3.])

In [9]:
arr = np.arange(-2, 7)
np.square(arr, arr)  # 通用函数并没有更改原有数组的值，如果需要更改原有数组的值，可以这样做
arr

array([ 4,  1,  0,  1,  4,  9, 16, 25, 36])