In [1]:
import numpy as np
# 切片返回的结果是原数组的视图
# 与python内建切片不一样的是，numpy中的切片是原数组的视图（与数据库的视图是一个道理），并不是复制的数据
# 原因在于numpy的设置初衷就是处理大型数组，如果默认为复制可能会引发内存问题，需要时可以显式复制数组

In [2]:
# 一维数组的切片与python内建的基本一致
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5:8]

array([5, 6, 7])

In [4]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [5]:
# 与python内建切片不一样的是，numpy中的切片是原数组的视图（与数据库的视图是一个道理），并不是复制的数据
# 原因在于numpy的设置初衷就是处理大型数组，如果默认为复制可能会引发内存问题，需要时可以显式复制数组
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [6]:
arr = np.arange(10)
arr_slice = arr[5:8].copy()  # 显式复制
arr_slice[:] = 64
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 2维数组的索引
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[0, 2]  # 也可以像C一样通过arr2d[0][2]的方式访问

3

In [8]:
# 2维数组的切片
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# 切片也可以像索引一样，用 , 隔开为多组，逐个维度进行切片
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [10]:
# 注意，这样写切片与上面的含义就不同了
arr2d[:2][1:]

array([[4, 5, 6]])

In [11]:
# 2维数组切片示例
arr2d[:2, 1:]
"""
array([[2, 3],
       [5, 6]])
"""

arr2d[1, :2]
"""
array([4, 5])
"""

arr2d[:2, 2]
"""
array([3, 6])
"""

arr2d[:, :1]
"""
array([[1],
       [4],
       [7]])
"""

'\narray([[1],\n       [4],\n       [7]])\n'

In [12]:
# 2维数组切片赋值
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])