In [1]:
import numpy as np
# 转置是一种特殊的数据重组形式，返回的底层数据的视图，而不需要复制任何内容

In [2]:
arr = np.arange(15).reshape((3, 5))
arr
"""
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
"""
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [3]:
# np.dot() 可以计算矩阵的内积
arr = np.arange(12).reshape((3, 4))
arr
"""
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
"""
np.dot(arr.T, arr)

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

In [4]:
np.dot(arr, arr.T)

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [5]:
arr = np.arange(16).reshape((2, 2, 4))
arr
"""
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])
"""
arr.transpose((1, 0, 2))  # transpose()接收包含轴编号的元祖，用于置换轴（轴重新排序）
# 这里使原先第2个轴变为第1个，原先第1个轴变为第2个，最后一个轴不变

# np.random.randn(x, y, z)  这里1轴是x， 2轴是y， 3轴是z，画一个正方体，将4个一维数组写到对应的棱上，分析一下就明白了

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [6]:
arr = np.arange(16).reshape((2, 2, 4))
arr
"""
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])
"""
arr.swapaxes(1, 2)  # swapaxes()接收一对轴编号作为参数，并对轴进行调整用于数据重组
# swapaxes()返回的是数据的视图，并没有对数据进行复制

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])