In [1]:
import numpy as np
# 线性代数，比如矩阵乘法、分解、行列式等方阵数学，是所有数组类库的重要组成部分。

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])
x.dot(y)  # <==> np.dot(x, y)

array([[ 28,  64],
       [ 67, 181]])

In [3]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [4]:
# @ 在numpy中也是点积的运算符号
x @ np.ones(3)

array([ 6., 15.])

In [5]:
from numpy.linalg import inv, qr
# numpy.linalg是numpy中的线性代数的标准函数集，使用的都是BLAS、LAPACK或因特尔专有的MKL库（具体看numpy的版本，matlab，R也使用这些库）

In [6]:
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)  # inv() 计算方阵的逆矩阵

array([[ 0.1537943 , -0.08442595, -0.07143393, -0.11444867, -0.05281834],
       [-0.08442595,  0.4621337 ,  0.49641129,  0.95811089,  0.33978032],
       [-0.07143393,  0.49641129,  1.09326012,  1.39112079,  0.33615962],
       [-0.11444867,  0.95811089,  1.39112079,  2.63445417,  0.87575247],
       [-0.05281834,  0.33978032,  0.33615962,  0.87575247,  1.12720774]])

In [7]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  6.93889390e-18,  1.11022302e-16,
         5.55111512e-17,  8.32667268e-17],
       [-8.67361738e-18,  1.00000000e+00,  9.99200722e-16,
         8.32667268e-16,  4.44089210e-16],
       [-1.04083409e-17, -1.66533454e-16,  1.00000000e+00,
        -1.27675648e-15,  0.00000000e+00],
       [-6.93889390e-18, -5.27355937e-16, -9.43689571e-16,
         1.00000000e+00, -4.44089210e-16],
       [ 0.00000000e+00, -5.55111512e-17, -1.11022302e-16,
        -2.22044605e-16,  1.00000000e+00]])

In [8]:
q, r = qr(mat)  # qr()计算QR分解
r

array([[-8.16350378, -6.55791253, -0.76628169,  2.52997151, -0.15515972],
       [ 0.        , -8.76072013, -0.70740044,  3.67570353,  0.02121647],
       [ 0.        ,  0.        , -3.37108388,  2.22910048, -0.84641653],
       [ 0.        ,  0.        ,  0.        , -0.5600906 ,  1.01055904],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.66390124]])