In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### 1. numpy.random.rand()

numpy.random.rand(d0, d1, …, dn)
- rand函数根据给定维度生成[0, 1)之间的数据
- dn表示每个维度
- 返回值为指定维度的array

In [2]:
np.random.rand(3, 4)

array([[0.64187127, 0.16879489, 0.05896359, 0.65001722],
       [0.70103247, 0.84932578, 0.38105484, 0.85075995],
       [0.40843969, 0.42196029, 0.04349731, 0.56695265]])

In [3]:
np.random.rand(2, 3, 4)

array([[[0.84871906, 0.54129695, 0.95852663, 0.45277871],
        [0.63560563, 0.16464007, 0.10891437, 0.95528538],
        [0.41333255, 0.31241563, 0.19829334, 0.15629672]],

       [[0.05924775, 0.16667177, 0.84008856, 0.4214843 ],
        [0.44009858, 0.11253956, 0.16589744, 0.92665323],
        [0.85952062, 0.98849685, 0.79010356, 0.9214918 ]]])

### 2. numpy.random.randn()

numpy.random.randn(d0, d1, …, dn)
- randn函数返回一个或一组样本，具有标准正态分布。
- dn表示每个维度
- 返回值为指定维度的array

标准正态分布介绍
- 标准正态分布——standard normal distribution
- 标准正态分布又称为u分布，是以0为均值、以1为标准差的正态分布，记为N(0, 1)。

In [4]:
np.random.randn(3, 4)

array([[-0.06142066,  0.871221  ,  1.76568362, -0.53816431],
       [ 1.69668154,  1.41519296,  0.01175847,  0.31070946],
       [-0.59932108,  2.02763487,  0.33461646,  0.61706808]])

In [5]:
np.random.randn(2, 3, 4)

array([[[ 0.60529116, -0.24637723, -1.05593973,  1.32571108],
        [-0.71297982,  1.07925064, -0.07031819, -0.6927889 ],
        [-3.05256708,  1.04331259, -1.1679736 , -0.97527986]],

       [[ 0.57841124, -2.36483328,  0.38286465,  0.05272806],
        [ 0.32764239, -0.6630138 , -2.7211279 ,  0.24494184],
        [ 0.896817  ,  0.55442119, -0.38139751, -0.19086462]]])

### 3. numpy.random.randint()

#### 3.1 numpy.random.randint()

numpy.random.randint(low, high=None, size=None, dtype=’l’)

- 返回随机整数，范围区间为[low, high)
- 参数：low为最小值，high为最大值，size为数组维度大小，dtype为数据类型，默认的数据类型是np.int
- high没有填写时，默认生成随机数的范围是[0, low)

In [6]:
np.random.randint(1, size=5)  # 返回[0, 1)之间的整数，所以只有0

array([0, 0, 0, 0, 0])

In [7]:
np.random.randint(1, 5)       # 返回1个[1, 5)之间的随机整数

3

In [8]:
np.random.randint(-5, 5, size=(2,2))

array([[-5, -2],
       [-2, -5]])

#### 3.2 numpy.random.random_integers

numpy.random.random_integers(low, high=None, size=None)
- 返回随机整数，范围区间为[low, high]
- 参数：low为最小值，high为最大值，size为数组维度大小
- high没有填写时，默认生成随机数的范围是[1, low]

该函数在最新的numpy版本中已被替代，建议使用randint函数

In [9]:
np.random.random_integers(1, size=5)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 1 + 1) instead
  """Entry point for launching an IPython kernel.


array([1, 1, 1, 1, 1])

### 4. 生成[0, 1)之间的浮点数

- numpy.random.random_sample(size=None)
- numpy.random.random(size=None)
- numpy.random.ranf(size=None)
- numpy.random.sample(size=None)

In [10]:
print('---------- random_sample ----------')
print(np.random.random_sample(size=(2,2)))
print('----------    random     ----------')
print(np.random.random(size=(2,2)))
print('----------     ranf      ----------')
print(np.random.ranf(size=(2,2)))
print('----------    sample     ----------')
print(np.random.sample(size=(2,2)))

---------- random_sample ----------
[[0.26294807 0.6344386 ]
 [0.90584778 0.61906136]]
----------    random     ----------
[[0.57885931 0.93922072]
 [0.56413863 0.38910148]]
----------     ranf      ----------
[[0.48218566 0.44484948]
 [0.04890879 0.72096341]]
----------    sample     ----------
[[0.84167044 0.78361446]
 [0.08046437 0.49651845]]


### 5. numpy.random.choice()

numpy.random.choice(a, size=None, replace=True, p=None)
- 从给定的一维数组中生成随机数
- 参数：a为一维数组类似数据或整数；size为数组维度；p为数组中的数据出现的概率
- a为整数时，对应的一维数组为np.arange(a)

In [11]:
np.random.choice(5, 3)

array([2, 1, 4])

In [12]:
np.random.choice(5, 3, replace=False)  # 当replace为False时，生成的随机数不能有重复的数值

array([2, 3, 0])

In [13]:
np.random.choice(5, size=(3, 4))

array([[1, 4, 0, 0],
       [2, 1, 3, 0],
       [4, 2, 1, 4]])

In [14]:
demo_list = ['huawei', 'xiaomi', 'oppo', 'vivo', 'nokia', 'moto']
np.random.choice(demo_list, size=(3,3))

array([['oppo', 'nokia', 'oppo'],
       ['huawei', 'moto', 'huawei'],
       ['huawei', 'vivo', 'moto']], dtype='<U6')

- 参数p的长度与参数a的长度需要一致
- 参数p为概率，p里的数据之和应为1

In [15]:
demo_list = ['huawei', 'xiaomi', 'oppo', 'vivo', 'nokia', 'moto']
p_list = [0.1, 0.5, 0.1, 0.1, 0.1, 0.1]
np.random.choice(demo_list, size=(3,3), p=p_list)

array([['oppo', 'vivo', 'oppo'],
       ['vivo', 'xiaomi', 'huawei'],
       ['xiaomi', 'vivo', 'moto']], dtype='<U6')

### 6. numpy.random.seed()
- np.random.seed()的作用：使得随机数据可预测。
- 当我们设置相同的seed，每次生成的随机数相同。如果不设置seed，则每次会生成不同的随机数

In [16]:
np.random.seed(1676)
np.random.rand(5)

array([0.39983389, 0.29426895, 0.89541728, 0.71807369, 0.3531823 ])

In [17]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [18]:
np.random.seed(1676)
np.random.rand(5)

array([0.39983389, 0.29426895, 0.89541728, 0.71807369, 0.3531823 ])