In [1]:
import numpy as np

# numpy的数组与python内建的数组不同，其运行更快，并占用内存更少
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list = [x*2 for x in my_list]

CPU times: user 12.8 ms, sys: 63.9 ms, total: 76.6 ms
Wall time: 78 ms
CPU times: user 996 ms, sys: 140 ms, total: 1.14 s
Wall time: 1.14 s


In [9]:
import numpy as np

# 生成随机数组，data是一个ndarray对象，是numpy的N-维数组
data = np.random.randn(2, 3)
data

array([[-0.0094954 , -0.6707879 ,  1.48206492],
       [ 0.11391168, -0.70210776,  1.24209268]])

In [10]:
# numpy中的数组操作，不必写循环
data * 10

array([[-0.09495401, -6.70787896, 14.82064923],
       [ 1.13911677, -7.02107762, 12.42092685]])

In [11]:
# numpy中的数组操作，不必写循环
data + data

array([[-0.0189908 , -1.34157579,  2.96412985],
       [ 0.22782335, -1.40421552,  2.48418537]])

In [14]:
# ndim属性表示ndarray的维度
data.ndim

2

In [12]:
# shape属性表示ndarray每一维的数量
data.shape

(2, 3)

In [13]:
# dtype属性表示ndarrau的数据类型
data.dtype

dtype('float64')