In [1]:
import numpy as np

In [2]:
# 指定数据类型
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [3]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [4]:
# 更改数据类型
arr = np.array([1, 2, 3, 4])
arr.dtype  # dtype('int64')
arr_float = arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [5]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric = numeric_strings.astype(float)
numeric.dtype

dtype('float64')

In [6]:
# 数组无需for循环即可进行批量操作，这种特性俗称“向量化”
# 任何两个等尺寸数组之间的算术运算都应用了逐个元素的操作方式
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [7]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [8]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [9]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [10]:
arr2 = np.array([[0, 4, 1], [7, 2, 12]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [11]:
# 如果两个不同尺寸的数组进行运算，将会用到广播特性，这里先不研究。