In [1]:
import numpy as np
# 布尔索引与切片不同，返回的结果总是数据的拷贝（一个新的数组），而不是原数组的视图

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names == 'Bob'  # == 也是可以向量化的，所以结果是一个数组

array([ True, False, False,  True, False, False, False])

In [3]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [4]:
data = np.random.randn(7, 4)  # 生成一个 7*4 的数组，假设names的每个人名都和data中的一行相对应
data[names=='Bob']  # 结果就是对应的行

array([[ 1.23305382, -1.14225616, -0.77872389, -0.71998641],
       [ 0.59435921, -2.09856187, -0.21881508,  0.80519745]])

In [5]:
data[names=='Bob', 2:]

array([[-0.77872389, -0.71998641],
       [-0.21881508,  0.80519745]])

In [6]:
data[names=='Bob', 3]

array([-0.71998641,  0.80519745])

In [7]:
data[names != 'Bob']

array([[-0.61815629, -0.49173547, -1.60530324,  0.76720814],
       [ 0.1808953 , -0.72225032, -1.53012066, -0.24985851],
       [ 1.31524326,  0.70751654,  0.48863911,  1.11010761],
       [-0.35787644,  0.79271724, -1.22031861,  0.58500956],
       [ 0.50562878,  1.13105251, -0.5685474 ,  1.11971173]])

In [8]:
data[~(names == 'Bob')]

array([[-0.61815629, -0.49173547, -1.60530324,  0.76720814],
       [ 0.1808953 , -0.72225032, -1.53012066, -0.24985851],
       [ 1.31524326,  0.70751654,  0.48863911,  1.11010761],
       [-0.35787644,  0.79271724, -1.22031861,  0.58500956],
       [ 0.50562878,  1.13105251, -0.5685474 ,  1.11971173]])

In [9]:
cond = names == 'Bob'
data[~cond]

array([[-0.61815629, -0.49173547, -1.60530324,  0.76720814],
       [ 0.1808953 , -0.72225032, -1.53012066, -0.24985851],
       [ 1.31524326,  0.70751654,  0.48863911,  1.11010761],
       [-0.35787644,  0.79271724, -1.22031861,  0.58500956],
       [ 0.50562878,  1.13105251, -0.5685474 ,  1.11971173]])

In [10]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [11]:
data[mask]

array([[ 1.23305382, -1.14225616, -0.77872389, -0.71998641],
       [ 0.1808953 , -0.72225032, -1.53012066, -0.24985851],
       [ 0.59435921, -2.09856187, -0.21881508,  0.80519745],
       [ 1.31524326,  0.70751654,  0.48863911,  1.11010761]])

In [12]:
# 将data中所有的负值设置为0
data[data<0] = 0
data

array([[1.23305382, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.76720814],
       [0.1808953 , 0.        , 0.        , 0.        ],
       [0.59435921, 0.        , 0.        , 0.80519745],
       [1.31524326, 0.70751654, 0.48863911, 1.11010761],
       [0.        , 0.79271724, 0.        , 0.58500956],
       [0.50562878, 1.13105251, 0.        , 1.11971173]])

In [13]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.76720814],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.79271724, 0.        , 0.58500956],
       [0.50562878, 1.13105251, 0.        , 1.11971173]])