In [2]:
import numpy as np
# 布尔索引与切片不同，返回的结果总是数据的拷贝（一个新的数组），而不是原数组的视图

In [5]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names == 'Bob'  # == 也是可以向量化的，所以结果是一个数组

array([ True, False, False,  True, False, False, False])

In [9]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [6]:
data = np.random.randn(7, 4)  # 生成一个 7*4 的数组，假设names的每个人名都和data中的一行相对应
data[names=='Bob']  # 结果就是对应的行

array([[ 1.84972868, -0.85585618,  0.50448047, -0.4572456 ],
       [-0.00923119,  0.27228254, -1.91686161, -0.92598438]])

In [7]:
data[names=='Bob', 2:]

array([[ 0.50448047, -0.4572456 ],
       [-1.91686161, -0.92598438]])

In [8]:
data[names=='Bob', 3]

array([-0.4572456 , -0.92598438])

In [10]:
data[names != 'Bob']

array([[-1.47730047,  0.14549192, -1.46203688,  0.55377789],
       [ 0.65693158, -0.02083748, -1.49239285, -0.75485228],
       [-0.47788109,  0.10138644,  0.42193838, -0.3339573 ],
       [-0.16311116, -1.46782665,  1.6184682 , -0.26415843],
       [-0.86385921,  0.48971784, -1.12547939,  0.12480623]])

In [11]:
data[~(names == 'Bob')]

array([[-1.47730047,  0.14549192, -1.46203688,  0.55377789],
       [ 0.65693158, -0.02083748, -1.49239285, -0.75485228],
       [-0.47788109,  0.10138644,  0.42193838, -0.3339573 ],
       [-0.16311116, -1.46782665,  1.6184682 , -0.26415843],
       [-0.86385921,  0.48971784, -1.12547939,  0.12480623]])

In [12]:
cond = names == 'Bob'
data[~cond]

array([[-1.47730047,  0.14549192, -1.46203688,  0.55377789],
       [ 0.65693158, -0.02083748, -1.49239285, -0.75485228],
       [-0.47788109,  0.10138644,  0.42193838, -0.3339573 ],
       [-0.16311116, -1.46782665,  1.6184682 , -0.26415843],
       [-0.86385921,  0.48971784, -1.12547939,  0.12480623]])

In [13]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [14]:
data[mask]

array([[ 1.84972868, -0.85585618,  0.50448047, -0.4572456 ],
       [ 0.65693158, -0.02083748, -1.49239285, -0.75485228],
       [-0.00923119,  0.27228254, -1.91686161, -0.92598438],
       [-0.47788109,  0.10138644,  0.42193838, -0.3339573 ]])

In [15]:
# 将data中所有的负值设置为0
data[data<0] = 0
data

array([[1.84972868, 0.        , 0.50448047, 0.        ],
       [0.        , 0.14549192, 0.        , 0.55377789],
       [0.65693158, 0.        , 0.        , 0.        ],
       [0.        , 0.27228254, 0.        , 0.        ],
       [0.        , 0.10138644, 0.42193838, 0.        ],
       [0.        , 0.        , 1.6184682 , 0.        ],
       [0.        , 0.48971784, 0.        , 0.12480623]])

In [16]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.14549192, 0.        , 0.55377789],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.6184682 , 0.        ],
       [0.        , 0.48971784, 0.        , 0.12480623]])