In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [19]:
rate = 7.0
nsteps = 100
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws>0, 0.995, 1.005)
steps

array([1.005, 0.995, 0.995, 0.995, 1.005, 1.005, 0.995, 1.005, 0.995,
       0.995, 0.995, 1.005, 0.995, 0.995, 0.995, 0.995, 0.995, 0.995,
       0.995, 0.995, 1.005, 0.995, 1.005, 0.995, 1.005, 1.005, 0.995,
       1.005, 0.995, 0.995, 1.005, 1.005, 0.995, 1.005, 0.995, 1.005,
       0.995, 1.005, 1.005, 1.005, 1.005, 1.005, 0.995, 0.995, 0.995,
       1.005, 0.995, 1.005, 0.995, 1.005, 0.995, 1.005, 1.005, 1.005,
       1.005, 1.005, 1.005, 1.005, 0.995, 0.995, 0.995, 1.005, 1.005,
       1.005, 1.005, 0.995, 0.995, 1.005, 0.995, 1.005, 1.005, 1.005,
       0.995, 0.995, 0.995, 0.995, 1.005, 0.995, 0.995, 1.005, 0.995,
       0.995, 1.005, 1.005, 0.995, 1.005, 0.995, 0.995, 0.995, 1.005,
       0.995, 1.005, 0.995, 0.995, 0.995, 1.005, 1.005, 0.995, 1.005,
       0.995])

In [20]:
truestep = steps.cumprod()
truestep

array([1.005     , 0.999975  , 0.99497512, 0.99000025, 0.99495025,
       0.999925  , 0.99492538, 0.9999    , 0.9949005 , 0.989926  ,
       0.98497637, 0.98990125, 0.98495175, 0.98002699, 0.97512685,
       0.97025122, 0.96539996, 0.96057296, 0.9557701 , 0.95099125,
       0.9557462 , 0.95096747, 0.95572231, 0.9509437 , 0.95569842,
       0.96047691, 0.95567452, 0.9604529 , 0.95565063, 0.95087238,
       0.95562674, 0.96040488, 0.95560285, 0.96038087, 0.95557896,
       0.96035686, 0.95555507, 0.96033285, 0.96513451, 0.96996018,
       0.97480998, 0.97968403, 0.97478561, 0.96991169, 0.96506213,
       0.96988744, 0.965038  , 0.96986319, 0.96501388, 0.96983894,
       0.96498975, 0.9698147 , 0.97466377, 0.97953709, 0.98443478,
       0.98935695, 0.99430374, 0.99927525, 0.99427888, 0.98930748,
       0.98436095, 0.98928275, 0.99422916, 0.99920031, 1.00419631,
       0.99917533, 0.99417945, 0.99915035, 0.9941546 , 0.99912537,
       1.004121  , 1.0091416 , 1.0040959 , 0.99907542, 0.99408

In [21]:
truerate = truestep * rate 
truerate

array([7.035     , 6.999825  , 6.96482587, 6.93000175, 6.96465175,
       6.99947501, 6.96447764, 6.99930003, 6.96430353, 6.92948201,
       6.8948346 , 6.92930877, 6.89466223, 6.86018892, 6.82588797,
       6.79175853, 6.75779974, 6.72401074, 6.69039069, 6.65693873,
       6.69022343, 6.65677231, 6.69005617, 6.65660589, 6.68988892,
       6.72333836, 6.68972167, 6.72317028, 6.68955443, 6.65610666,
       6.68938719, 6.72283413, 6.68921996, 6.72266606, 6.68905273,
       6.72249799, 6.6888855 , 6.72232993, 6.75594158, 6.78972128,
       6.82366989, 6.85778824, 6.8234993 , 6.7893818 , 6.75543489,
       6.78921207, 6.75526601, 6.78904234, 6.75509713, 6.78887261,
       6.75492825, 6.78870289, 6.8226464 , 6.85675964, 6.89104343,
       6.92549865, 6.96012615, 6.99492678, 6.95995214, 6.92515238,
       6.89052662, 6.92497925, 6.95960415, 6.99440217, 7.02937418,
       6.99422731, 6.95925617, 6.99405245, 6.95908219, 6.9938776 ,
       7.02884699, 7.06399123, 7.02867127, 6.99352791, 6.95856

In [42]:
percnt = 10000
rmb = 70000
doller = 10000
pool = 98 * 10000
pooltime = [100*10000]
for i in range(100):
    if(i%2 == 0): 
        rmb += percnt * truerate[i]
        doller += percnt
        pool -= (percnt*2)
    else:
        if(steps[i] == 0.995):
            ratelast = rate if(i==0) else truerate[i-1]
            rmb -= percnt * ratelast
            pool += percnt * ratelast / truerate[i]
        else:
            doller -= percnt
            rmb += percnt * truerate[i]
    # pooltime.append[rmb/truerate[i]+doller+pool]
    print(i, '\t', rmb, '\t', rmb/truerate[i], '\t', doller, '\t', pool, '\t', rmb/truerate[i]+doller+pool, '\t', truerate[i])

0 	 140350.0 	 19950.24875621891 	 20000 	 960000 	 999950.2487562189 	 7.034999999999999
1 	 70000.00000000001 	 10000.25000625016 	 20000 	 970050.2512562814 	 1000050.5012625315 	 6.999824999999999
2 	 139648.25875 	 20050.502518844383 	 30000 	 950050.2512562814 	 1000100.7537751258 	 6.964825874999999
3 	 70000.00000000001 	 10101.007556627519 	 30000 	 960100.5025125628 	 1000201.5100691903 	 6.930001745624999
4 	 139646.51754353126 	 20050.753787689075 	 40000 	 940100.5025125628 	 1000151.2563002518 	 6.964651754353124
5 	 209641.26767478016 	 29950.998793720475 	 30000 	 940100.5025125628 	 1000051.5013062833 	 6.999475013124889
6 	 279286.0440553728 	 40101.50632534721 	 40000 	 920100.5025125628 	 1000202.00883791 	 6.964477638059265
7 	 349279.0443178684 	 49901.99634362908 	 30000 	 920100.5025125628 	 1000002.4988561919 	 6.99930002624956
8 	 418922.0795790515 	 60152.76014435083 	 40000 	 900100.5025125628 	 1000253.2626569136 	 6.964303526118312
9 	 349279.0443178684 	 

84 	 3563609.0208761455 	 517330.310765466 	 190000 	 290854.2713567837 	 998184.5821222496 	 6.888459745579693
85 	 3632838.0413192213 	 524756.5281248419 	 180000 	 290854.2713567837 	 995610.7994816256 	 6.922902044307591
86 	 3701720.9166600816 	 537393.495602856 	 190000 	 270854.2713567837 	 998247.7669596397 	 6.888287534086053
87 	 3632838.0413192213 	 530043.7141737248 	 190000 	 280904.5226130651 	 1000948.2367867898 	 6.853846096415622
88 	 3701033.809978557 	 542707.250425854 	 200000 	 260904.52261306508 	 1003611.7730389191 	 6.819576865933544
89 	 3769570.557481189 	 550007.2143540836 	 190000 	 260904.52261306508 	 1000911.7369671487 	 6.853674750263211
90 	 3837764.6212463076 	 562771.0697025966 	 200000 	 240904.52261306508 	 1003675.5923156617 	 6.819406376511895
91 	 3906299.6553302524 	 569971.2136344246 	 190000 	 240904.52261306508 	 1000875.7362474897 	 6.853503408394454
92 	 3974492.0142437774 	 582835.3905873614 	 200000 	 220904.52261306508 	 1003739.91320042