In [1]:
import numpy as np

In [2]:
x = np.random.randn(8)

In [3]:
y = np.random.randn(8)

In [4]:
x

array([-0.48176014, -1.43302492,  0.18482976, -0.48004132, -0.17595301,
        1.15827578, -1.46562191, -0.07930319])

In [5]:
y

array([-1.18816421,  1.43530899, -0.65332027, -1.44350933,  0.20151107,
        0.68795086,  0.86118625,  0.08341092])

In [7]:
x = np.array([-0.48, -1.43,  0.18, -0.48, -0.17, 1.15, -1.46, -0.07])  # x = np.random.randn(8)

In [8]:
x

array([-0.48, -1.43,  0.18, -0.48, -0.17,  1.15, -1.46, -0.07])

In [9]:
y = np.array([-1.18,  1.43, -0.65, -1.44,  0.20, 0.68,  0.86,  0.08])  # y = np.random.randn(8)

In [10]:
y

array([-1.18,  1.43, -0.65, -1.44,  0.2 ,  0.68,  0.86,  0.08])

In [11]:
arr = np.random.randn(7) * 5
arr

array([-10.8559669 ,  -1.80834201,  -0.37794136,  -6.58140078,
         8.89418456,   5.8311316 ,   3.21878654])

In [12]:
arr = np.array([-10.85, -1.80, -0.37, -6.58, 8.89, 5.83, 3.21])  # arr = np.random.randn(7) * 5
arr

array([-10.85,  -1.8 ,  -0.37,  -6.58,   8.89,   5.83,   3.21])

In [20]:
arr = np.arange(-2, 7)
arr

array([-2, -1,  0,  1,  2,  3,  4,  5,  6])

In [16]:
np.square(arr)

array([ 4,  1,  0,  1,  4,  9, 16, 25, 36])

In [18]:
np.square(arr, arr)

array([ 4,  1,  0,  1,  4,  9, 16, 25, 36])

In [21]:
arr

array([-2, -1,  0,  1,  2,  3,  4,  5,  6])

In [25]:
points = np.arange(4)
points

array([0, 1, 2, 3])

In [26]:
np.meshgrid(points, points)

[array([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]),
 array([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])]

In [27]:
np.meshgrid(points, points, points)

[array([[[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],
 
        [[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],
 
        [[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],
 
        [[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]]]),
 array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],
 
        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]]),
 array([[[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]],
 
        [[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]],
 
        [[0, 1, 2, 3],
         [0, 1, 2, 3],
    

In [28]:
points = np.arange(-5, 5, 0.01)  # 1000个等间距的点
xs, ys = np.meshgrid(points, points)  # np.meshgrid()接收两个一维数组，根据两个数组的所有(x,y)对生成一个二维矩阵

In [29]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [30]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [31]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]